// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Domain_Modal;

/************************************************************/
/**
 * 
 */
public class Customer extends User {
	/**
	 * 
	 */
	private String c_name;
	/**
	 * 
	 */
	private String address;
	/**
	 * 
	 */
	public String email;
	/**
	 * 
	 */
	private String creditCard;
	/**
	 * 
	 */
	private float bal;

	/**
	 * 
	 */
	public void login() {
	}

	/**
	 * 
	 */
	public void register() {
	}

	/**
	 * 
	 */
	public void updateProfile() {
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getC_name() {
		return c_name;
	}

	public void setC_name(String c_name) {
		this.c_name = c_name;
	}

	public float getBal() {
		return bal;
	}

	public void setBal(float bal) {
		this.bal = bal;
	}

	public String getCreditCard() {
		return creditCard;
	}

	public void setCreditCard(String creditCard) {
		this.creditCard = creditCard;
	}
}
