// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Domain_Modal;

/************************************************************/
/**
 * 
 */
public class OrderDetails {
	/**
	 * 
	 */
	private int order_id;
	/**
	 * 
	 */
	private float unitCost;
	/**
	 * 
	 */
	private float total;
	/**
	 * 
	 */
	private String prduct_id;
	/**
	 * 
	 */
	private String prduct_name;
	/**
	 * 
	 */
	private int quantity;

	/**
	 * 
	 */
	public Order ;
	/**
	 * 
	 */
	public void calcBill() {
	}
}
