// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Domain_Modal;

/************************************************************/
/**
 * 
 */
public class Order {
	/**
	 * 
	 */
	private int orderID;
	/**
	 * 
	 */
	private String orderDate;
	/**
	 * 
	 */
	private String shipped_date;
	/**
	 * 
	 */
	private String c_name;
	/**
	 * 
	 */
	private String c_id;
	/**
	 * 
	 */
	private String shipping_id;
	/**
	 * 
	 */
	private String status;

	/**
	 * 
	 */
	public Customer;
	/**
	 * 
	 */
	public void p_order() {
	}
}
