// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Domain_Modal;

/************************************************************/
/**
 * 
 */
public class Product_books {
	/**
	 * 
	 */
	private String product_id;
	/**
	 * 
	 */
	private float price;
	/**
	 * 
	 */
	private String pro_name;
	/**
	 * 
	 */
	private int quantity;
	/**
	 * 
	 */
	private String genre;

	/**
	 * 
	 * @return 
	 */
	public String getProductid() {
	}
}
