// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Domain_Modal;

/************************************************************/
/**
 * 
 */
public class ShippingInfo {
	/**
	 * 
	 */
	private String shipping_id;
	/**
	 * 
	 */
	private float cost;
	/**
	 * 
	 */
	private int zipcode;

	/**
	 * 
	 */
	public Order ;
	/**
	 * 
	 */
	public void UpdateShipInfo() {
	}
}
