// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Domain_Modal;

/************************************************************/
/**
 * 
 */
public class ShoppingCart {
	/**
	 * 
	 */
	private int cart_id;
	/**
	 * 
	 */
	private int pro_id;
	/**
	 * 
	 */
	private int quantity;

	/**
	 * 
	 */
	public Customer;
	/**
	 * 
	 */
	public void addItem() {
	}

	/**
	 * 
	 */
	public void updateQuantity() {
	}

	/**
	 * 
	 */
	public void deleteItem() {
	}

	/**
	 * 
	 */
	public void checkOut() {
	}
}
