// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Domain_Modal;

/************************************************************/
/**
 * 
 */
public class User {
	/**
	 * 
	 */
	private String id;
	/**
	 * 
	 */
	private String pass;
	/**
	 * 
	 */
	private String registerDate;

	/**
	 * 
	 * @return 
	 */
	public boolean verify() {
		return false;
	}

	public String getRegisterDate() {
		return registerDate;
	}

	public void setRegisterDate(String registerDate) {
		this.registerDate = registerDate;
	}

	public String getPass() {
		return pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
}
