// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 19K-0354_A2;



/************************************************************/
/**
 * 
 */
public class Books extends Items
 {
				/**
				 * 
				 */
				public String language;
				/**
				 * 
				 */
				public Author author;
				/**
				 * 
				 */
				public Publisher[] publisher;
}
