// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 19K-0354_A2;



/************************************************************/
/**
 * 
 */
public class Borrow {
				/**
				 * 
				 */
				public EcorePrimitiveTypes.EDate start_date;
				/**
				 * 
				 */
				public EcorePrimitiveTypes.EDate end_date;
	/**
	 * 
	 */
	public void add() {
	}
	/**
	 * 
	 */
	public void remove() {
	}
	/**
	 * 
	 */
	public void update() {
	}
}
