// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 19K-0354_A2;



/************************************************************/
/**
 * 
 */
public class DCL_LIB {
				/**
				 * 
				 */
				public String name;
				/**
				 * 
				 */
				private String password;
				/**
				 * 
				 */
				public Lib_Clerk lib_clerk;
				/**
				 * 
				 */
				public Items[] items;
				/**
				 * 
				 */
				public Supplier[] supplier;
	/**
	 * 
	 */
	public void updateItems() {
	}
}
