// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 19K-0354_A2;



/************************************************************/
/**
 * 
 */
public class Items {
				/**
				 * 
				 */
				public String collection_num;
				/**
				 * 
				 */
				public String title;
				/**
				 * 
				 */
				public String ISBN;
				/**
				 * 
				 */
				public String condition;
	/**
	 * 
	 */
	public void viewItem() {
	}
}
