// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 19 K-0354_ A2;

/************************************************************/
/**
 * 
 */
public class Lib_Clerk {
	/**
	 * 
	 */
	public String clerk_id;
	/**
	 * 
	 */
	public String cler_id;
	/**
	 * 
	 */
	public String clerk_name;
	/**
				 * 
				 */
				public String phone#;
	/**
	 * 
	 */
	public User[] user;

	/**
	 * 
	 */
	public void addBook() {
	}

	/**
	 * 
	 */
	public void delete() {
	}

	/**
	 * 
	 */
	public void update() {
	}

	/**
	 * 
	 */
	public void calculate_fine() {
	}

	/**
	 * 
	 */
	public void search() {
	}
}
