// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 19 K-0354_ A2;

/************************************************************/
/**
 * 
 */
public class Supplier {
	/**
	 * 
	 */
	public String sup_id;
	/**
	 * 
	 */
	public String sup_name;
	/**
				 * 
				 */
				public String phone#;

	/**
	 * 
	 */
	public void showItems() {
	}

	/**
	 * 
	 */
	public void payement() {
	}
}
