// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 19 K-0354_ A2;

/************************************************************/
/**
 * 
 */
public class User {
	/**
	 * 
	 */
	public String userID;
	/**
	 * 
	 */
	public String address;
	/**
				 * 
				 */
				public String phone#;

	/**
	 * 
	 */
	public void selectItem() {
	}
}
