// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 19K-0354_A2;



/************************************************************/
/**
 * 
 */
public class Videos extends Items
 {
				/**
				 * 
				 */
				public String genre;
				/**
				 * 
				 */
				public Producer producer;
				/**
				 * 
				 */
				public Artist[] artist;
}
